### ISSUE TITLE
Format: incorrect use of Markdown heading level 2

### ISSUE THREAD

**Issue by pzhlkj6612** [Alafun/Alafun.github.io#1]
Hi.

https://github.com/Alafun/Alafun.github.io/blob/2744d22c79c347b28703672e999ef1a57743684e/post/about-me/index.html#L114

Source:

```diff
- ##⛹ Habit
+ ## ⛹ Habit
```

Rendered:

> ##⛹ Habit

> ## ⛹ Habit

**Comment by Alafun** [comment]
You are careful, thank you.

**Comment by pzhlkj6612** [comment]
Hi. I think you should not directly modify your GitHub Pages repository. This modification will be overwritten by your next deployment. Your blog's source code is not online, so I cannot make any Pull Requests.

**Comment by Alafun** [comment]
:-) The blog code is generated by [Gridea](https://gridea.dev/). But the repository has not been maintained for a long time.

**Comment by Alafun** [comment]
By the way, the app is also open source at ![github](https://github.com/getgridea/gridea).

**Comment by pzhlkj6612** [comment]
I mean, your **source** Markdown files are not public. Modifying the **generated** webpage is meaningless. You need to modify your Markdown file, then re-generate and publish your blog by Gridea.

<br>

> The blog code is generated by Gridea...  
> By the way, the app is also open source at [github](https://github.com/getgridea/gridea).

OK, I know that, thank you.

**Comment by Alafun** [comment]
> I mean, your **source** Markdown files are not public. Modifying the **generated** webpage is meaningless. You need to modify your Markdown file, then re-generate and publish your blog by Gridea.

Thank you.

I know, you means that the github pages is not change at all, so I should republish using Gridea to fix my blog. 

Maybe I will change the view of the blog after I master front-end knowledge

**Comment by pzhlkj6612** [comment]
> I know, you means that the github pages is not change at all, so I should republish using Gridea to fix my blog.

The reason why the content of GitHub Pages didn't change is because you modified the attribute in the [`<meta>` tag](https://github.com/Alafun/Alafun.github.io/blob/2e8f1a61a107f0ec21d5666f2f49bb30035ea18d/post/about-me/index.html#L14-L24) instead of the content in [`<body>`](https://github.com/Alafun/Alafun.github.io/blob/2e8f1a61a107f0ec21d5666f2f49bb30035ea18d/post/about-me/index.html#L107-L117) . So I recommend you to re-deploy your website by Gridea.

And, GitHub automatically updates your website based on the content of this repository, so the commit (2e8f1a61a107f0ec21d5666f2f49bb30035ea18d) has actually taken effect. You can check the source code of https://alafun.github.io/post/about-me/ (the 21st line) .

> Maybe I will change the view of the blog after I master front-end knowledge

OK, please take your time.
